### PR TITLE
Add parallel execution of file format

### PR DESCRIPTION
**Pull request by gaborbernat**

### CODE REVIEW

**Comment by gaborbernat** [comment]
Is this okay?

**Comment by gaborbernat** [comment]
Hello, added a commit with the fixes :)

**Comment by youribonnaffe** [comment]
Sorry I'm a pain in the ass :D I have one last comment ...

**Comment by gaborbernat** [comment]
Quick fixup :) Nice catch :+1:

**Comment by youribonnaffe** [comment]
Thank you

**Pull request merged**
