### PR TITLE
We can apply the Java plugin if the user failed to do so, instead of nagging him about it, and an extra test

### PR DESCRIPTION
**Pull request by gaborbernat**
All looks fine for me, can you make a release with the import order?

### CODE REVIEW

**Comment by gaborbernat** [comment]
Made the removing :)

**Comment by youribonnaffe** [comment]
Looks good to me, could you rebase the commits on master branch instead of this one?
(I don't know how if merging it myself would preserve the pull request).

Then I'll push a 1.2 to bintray

**Comment by gaborbernat** [comment]
Sure, I'll do it tomorrow morning :)

**Comment by gaborbernat** [comment]
According to this
https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request a
rebase preserve this information :)

**Comment by youribonnaffe** [comment]
I did it though it did not recognize this PR and closed it automatically

**Comment by gaborbernat** [comment]
Np:)

**Comment by gaborbernat** [comment]
Looks great for me :)

**Pull request closed without merging**
