### PR TITLE
Lazy config evaluation and parallel processing

### PR DESCRIPTION
**Pull request by gaborbernat**
Also removed the both groovy and java file for the import. The configuration parsing moved out of the task.

Some cleanup, cleaner test code. 

Made the config cleaner, use just 3 config tags, however allow multiple type of inputs. For instance an importOrder may be both an array, in case of a String a file, or closure otherwise. More helpful error messages, check can we read write files and alert if not.

### CODE REVIEW

**Comment by gaborbernat** [comment]
Let me know if there's anything I can help with :)

**Comment by gaborbernat** [comment]
Do you require anything from me for this? :)

**Comment by youribonnaffe** [comment]
I don't know, I was kind of waiting for you to change the PR after our discussion above :)

**Comment by gaborbernat** [comment]
So I see it, the issues are the missing description, plus do not abbreviate. Anything else, I'm missing?

**Comment by gaborbernat** [comment]
I'll probably also fix the merge issues of course :)

**Comment by youribonnaffe** [comment]
There was also the potential bug about import + format

**Comment by gaborbernat** [comment]
The bug does not manifests for the current order, format, then import.

**Comment by gaborbernat** [comment]
Trying to fix this, however some failing commit tests (Java 7, 8) really makes this hard. We'll let you know once I manage to fix it. In the meantime spotted a bug... for some reason the Java 7 test had 20 empty lines after the import set :open_mouth:

**Comment by gaborbernat** [comment]
Aborting this for now, as I cannot get the tests working. I'll start over this and push, in new pull requests, one per feature.

**Pull request closed without merging**
