### PR TITLE
Java 8 support progress

### PR DESCRIPTION
**Pull request by nedtwigg**
Looks like my "just update your dependency" suggestion was pretty naive of me, sorry!  It seems that public maven repos didn't have all of the transitives, and it was failing silently.

I went back to your last public release, then created a complicated Java 8 example that definitely fails (so that we can be sure we've fixed the issue when it passes).

Then I resolved the dependencies of the latest Eclipse by hand using a hacked-up ivy downloader to access Eclipse's official p2 repository (p2 is Eclipse's own special repository format.  I just finished building an installer that uses p2, and it was a nightmare, but it's the only way to get recent Eclipse artifacts).

When I run the tests in Eclipse (supposedly with the same class path), the formatter succeeds.  When I run them at the command line from gradle, it fails...

Since I'm this far in, I'm probably gonna take a chunk of tomorrow to just go all the way and add:
- a check task
- incremental formatting (only run on changed files)
- maybe license header enforcement (one formatting plugin to rule them all).

At least for me, I'm more comfortable doing this in Java, and I think I'm likely to write more new lines than currently exist in the project.

Totally understand if this is more than you bargained for and you'd prefer that I just forked.  I'll keep you up-to-date as I make progress (or as I get stuck ;-)

### CODE REVIEW

**Comment by nedtwigg** [comment]
Commit 1864180 makes the plugin deployable, and I confirmed that it works on my project, but a bunch of tests were failing in gradle that worked in Eclipse.

In the next one, Commit de41a1f, I moved the entire thing over to Java to see if that fixed it.  Now there are 2 tests that pass in Eclipse but fail in gradle. Running the plugin on real projects works great.

But there is yet another problem!  It seems that the keys in the "format.xml/properties" have changed since the old formatter.  Using the "format.xml" that was in the project, the formatter defaulted to using tabs even though the file clearly calls for spaces.  After making a new format.xml from a new version of eclipse, the spaces came back.

At the very least, this would need to be a `2.x` release to alert your users that they'll need to make new properties files using newer versions of Eclipse (I tested with the latest, which is 4.4.2).

Two days ago you had nice tidy project, and I've hacked it into monstrosity ;-).  And although it will likely break for most of your existing users, it's extremely useful to me.  So if you're not comfortable pushing a 2.0 that requires your existing users to upgrade their files, I'm happy to fork, and maybe after my fork has stabilized you can suck it back in.

**Comment by nedtwigg** [comment]
As of b29fe5, the plugin adds a "formatCheck" task, which depends on "check", and a "formatApply" task.  In order for them to be configured together, I added a "format" extension block.

It's now very easy to add license enforcement to this plugin as well, which would be useful for my case to make this a "total" package - one plugin to deal with all the formatting stuff that an open source Java plugin needs.  That'll be my next little project.

Since I've done so much butchering, I think it makes sense for me to start a fork, rather than ask you to maintain this big hunk of code.  If it's alright with you, I'll release the project on bintray as "com.diffplug.gradle.spotless-java", but I'll keep your `com.github.youribonnaffe.gradle.format` package names within the project's source code to pay homage and make it easy for us to share code if you decide to take the java parts of the formatter (I'm guessing you don't want the license formatter).

**Comment by youribonnaffe** [comment]
So you don't like Groovy :'( ? 
As you said I would indeed rather see the license header as a separate plugin (very simple one probably, and license could be applied to non Java files).
But I'd be happy to merge your improvements for Java 8 support I won't have much time to take a closer look this week and the one after.

**Comment by nedtwigg** [comment]
I'm a lot more effective in an IDE where I can refactor using automated tools, which is harder with dynamic languages.  I don't know much about Groovy tooling, so maybe that's possible with Groovy, but I think that `gradlew eclipse`, then import the project in any Eclipse with no special plugins, is a big win.  But it would definitely be possible to move the Java 8 stuff back to Groovy, the only real "hard part" was getting the build right.

**Comment by youribonnaffe** [comment]
It looks like because gradleApi() has a dependency on core-3.1.1 (from Eclipse) that it will conflict with the one we explicitly get. It looks like it is not even related to Java 8 here, just because there is an enum in the code is enough to break the formatting (the old one packaged by Gradle maybe does not support 1.5 / compiler options are not propagated).
By tweaking the classpath order and running the test, I can get the code properly formatted.
When using the plugin an enum is properly formatted....

Not sure how to get it to work with Java 8 though :/

**Comment by youribonnaffe** [comment]
And it looks it manages to format Java 8 code when used in a project, so the tests will fail but not when really used.

**Comment by youribonnaffe** [comment]
Thanks @nedtwigg for your comments, I'll close this issue as it seems to work

**Comment by selvarajchennappan** [comment]
plugins {
  id 'com.github.youribonnaffe.gradle.format'  version "1.3"
}

It is not working .

**Comment by youribonnaffe** [comment]
Yes indeed, version 1.2 is deployed on plugins.gradle.org

**Comment by selvarajchennappan** [comment]
Thanks
1. However it depends on Hibernate Tools .it requires lot of dependency.
2. Curly braces comes in the next line after class body declaration.

**Comment by selvarajchennappan** [comment]
Could please advise why junit test class is not formatted

plugins {
  id "com.github.youribonnaffe.gradle.format" version "1.2"
}

   apply plugin: 'com.github.youribonnaffe.gradle.format'
		format {
	configurationFile = file('../formatter_java_8.properties');
	importsOrder = ["java", "javax", "org", "com"]
	files = sourceSets.main.java + sourceSets.test.java
	}

**Comment by youribonnaffe** [comment]
Could please a separate issue for this as it does not relate to the current discussion.
And if you could provide a test project to illustrate the issue that would be great.

This line (files = sourceSets.main.java + sourceSets.test.java) is probably not needed as it should be the default.

**Pull request closed without merging**
